/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_jna_Native */

#ifndef _Included_com_sun_jna_Native
#define _Included_com_sun_jna_Native
#ifdef __cplusplus
extern "C" {
#endif
#undef com_sun_jna_Native_TYPE_VOIDP
#define com_sun_jna_Native_TYPE_VOIDP 0L
#undef com_sun_jna_Native_TYPE_LONG
#define com_sun_jna_Native_TYPE_LONG 1L
#undef com_sun_jna_Native_TYPE_WCHAR_T
#define com_sun_jna_Native_TYPE_WCHAR_T 2L
#undef com_sun_jna_Native_TYPE_SIZE_T
#define com_sun_jna_Native_TYPE_SIZE_T 3L
#undef com_sun_jna_Native_TYPE_BOOL
#define com_sun_jna_Native_TYPE_BOOL 4L
#undef com_sun_jna_Native_TYPE_LONG_DOUBLE
#define com_sun_jna_Native_TYPE_LONG_DOUBLE 5L
#undef com_sun_jna_Native_CB_HAS_INITIALIZER
#define com_sun_jna_Native_CB_HAS_INITIALIZER 1L
#undef com_sun_jna_Native_CVT_UNSUPPORTED
#define com_sun_jna_Native_CVT_UNSUPPORTED -1L
#undef com_sun_jna_Native_CVT_DEFAULT
#define com_sun_jna_Native_CVT_DEFAULT 0L
#undef com_sun_jna_Native_CVT_POINTER
#define com_sun_jna_Native_CVT_POINTER 1L
#undef com_sun_jna_Native_CVT_STRING
#define com_sun_jna_Native_CVT_STRING 2L
#undef com_sun_jna_Native_CVT_STRUCTURE
#define com_sun_jna_Native_CVT_STRUCTURE 3L
#undef com_sun_jna_Native_CVT_STRUCTURE_BYVAL
#define com_sun_jna_Native_CVT_STRUCTURE_BYVAL 4L
#undef com_sun_jna_Native_CVT_BUFFER
#define com_sun_jna_Native_CVT_BUFFER 5L
#undef com_sun_jna_Native_CVT_ARRAY_BYTE
#define com_sun_jna_Native_CVT_ARRAY_BYTE 6L
#undef com_sun_jna_Native_CVT_ARRAY_SHORT
#define com_sun_jna_Native_CVT_ARRAY_SHORT 7L
#undef com_sun_jna_Native_CVT_ARRAY_CHAR
#define com_sun_jna_Native_CVT_ARRAY_CHAR 8L
#undef com_sun_jna_Native_CVT_ARRAY_INT
#define com_sun_jna_Native_CVT_ARRAY_INT 9L
#undef com_sun_jna_Native_CVT_ARRAY_LONG
#define com_sun_jna_Native_CVT_ARRAY_LONG 10L
#undef com_sun_jna_Native_CVT_ARRAY_FLOAT
#define com_sun_jna_Native_CVT_ARRAY_FLOAT 11L
#undef com_sun_jna_Native_CVT_ARRAY_DOUBLE
#define com_sun_jna_Native_CVT_ARRAY_DOUBLE 12L
#undef com_sun_jna_Native_CVT_ARRAY_BOOLEAN
#define com_sun_jna_Native_CVT_ARRAY_BOOLEAN 13L
#undef com_sun_jna_Native_CVT_BOOLEAN
#define com_sun_jna_Native_CVT_BOOLEAN 14L
#undef com_sun_jna_Native_CVT_CALLBACK
#define com_sun_jna_Native_CVT_CALLBACK 15L
#undef com_sun_jna_Native_CVT_FLOAT
#define com_sun_jna_Native_CVT_FLOAT 16L
#undef com_sun_jna_Native_CVT_NATIVE_MAPPED
#define com_sun_jna_Native_CVT_NATIVE_MAPPED 17L
#undef com_sun_jna_Native_CVT_NATIVE_MAPPED_STRING
#define com_sun_jna_Native_CVT_NATIVE_MAPPED_STRING 18L
#undef com_sun_jna_Native_CVT_NATIVE_MAPPED_WSTRING
#define com_sun_jna_Native_CVT_NATIVE_MAPPED_WSTRING 19L
#undef com_sun_jna_Native_CVT_WSTRING
#define com_sun_jna_Native_CVT_WSTRING 20L
#undef com_sun_jna_Native_CVT_INTEGER_TYPE
#define com_sun_jna_Native_CVT_INTEGER_TYPE 21L
#undef com_sun_jna_Native_CVT_POINTER_TYPE
#define com_sun_jna_Native_CVT_POINTER_TYPE 22L
#undef com_sun_jna_Native_CVT_TYPE_MAPPER
#define com_sun_jna_Native_CVT_TYPE_MAPPER 23L
#undef com_sun_jna_Native_CVT_TYPE_MAPPER_STRING
#define com_sun_jna_Native_CVT_TYPE_MAPPER_STRING 24L
#undef com_sun_jna_Native_CVT_TYPE_MAPPER_WSTRING
#define com_sun_jna_Native_CVT_TYPE_MAPPER_WSTRING 25L
#undef com_sun_jna_Native_CVT_OBJECT
#define com_sun_jna_Native_CVT_OBJECT 26L
#undef com_sun_jna_Native_CVT_JNIENV
#define com_sun_jna_Native_CVT_JNIENV 27L
#undef com_sun_jna_Native_CVT_SHORT
#define com_sun_jna_Native_CVT_SHORT 28L
#undef com_sun_jna_Native_CVT_BYTE
#define com_sun_jna_Native_CVT_BYTE 29L
#undef com_sun_jna_Native_CB_OPTION_DIRECT
#define com_sun_jna_Native_CB_OPTION_DIRECT 1L
#undef com_sun_jna_Native_CB_OPTION_IN_DLL
#define com_sun_jna_Native_CB_OPTION_IN_DLL 2L
/*
 * Class:     com_sun_jna_Native
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     com_sun_jna_Native
 * Method:    setProtected
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_setProtected
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_sun_jna_Native
 * Method:    isProtected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_sun_jna_Native_isProtected
  (JNIEnv *, jclass);

/*
 * Class:     com_sun_jna_Native
 * Method:    _getDirectBufferPointer
 * Signature: (Ljava/nio/Buffer;)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_jna_Native__1getDirectBufferPointer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_sun_jna_Native
 * Method:    sizeof
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_sun_jna_Native_sizeof
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_sun_jna_Native
 * Method:    getNativeVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sun_jna_Native_getNativeVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_sun_jna_Native
 * Method:    getAPIChecksum
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sun_jna_Native_getAPIChecksum
  (JNIEnv *, jclass);

/*
 * Class:     com_sun_jna_Native
 * Method:    getLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sun_jna_Native_getLastError
  (JNIEnv *, jclass);

/*
 * Class:     com_sun_jna_Native
 * Method:    setLastError
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_setLastError
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_sun_jna_Native
 * Method:    unregister
 * Signature: (Ljava/lang/Class;[J)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_unregister
  (JNIEnv *, jclass, jclass, jlongArray);

/*
 * Class:     com_sun_jna_Native
 * Method:    registerMethod
 * Signature: (Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;[I[J[JIJJLjava/lang/reflect/Method;JIZ[Lcom/sun/jna/ToNativeConverter;Lcom/sun/jna/FromNativeConverter;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_jna_Native_registerMethod
  (JNIEnv *, jclass, jclass, jstring, jstring, jintArray, jlongArray, jlongArray, jint, jlong, jlong, jobject, jlong, jint, jboolean, jobjectArray, jobject, jstring);

/*
 * Class:     com_sun_jna_Native
 * Method:    ffi_prep_cif
 * Signature: (IIJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_jna_Native_ffi_1prep_1cif
  (JNIEnv *, jclass, jint, jint, jlong, jlong);

/*
 * Class:     com_sun_jna_Native
 * Method:    ffi_call
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_ffi_1call
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     com_sun_jna_Native
 * Method:    ffi_prep_closure
 * Signature: (JLcom/sun/jna/Native/ffi_callback;)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_jna_Native_ffi_1prep_1closure
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_sun_jna_Native
 * Method:    ffi_free_closure
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_ffi_1free_1closure
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sun_jna_Native
 * Method:    initialize_ffi_type
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sun_jna_Native_initialize_1ffi_1type
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sun_jna_Native
 * Method:    freeNativeCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_freeNativeCallback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sun_jna_Native
 * Method:    createNativeCallback
 * Signature: (Lcom/sun/jna/Callback;Ljava/lang/reflect/Method;[Ljava/lang/Class;Ljava/lang/Class;IILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_jna_Native_createNativeCallback
  (JNIEnv *, jclass, jobject, jobject, jobjectArray, jclass, jint, jint, jstring);

/*
 * Class:     com_sun_jna_Native
 * Method:    invokeInt
 * Signature: (Lcom/sun/jna/Function;JI[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_sun_jna_Native_invokeInt
  (JNIEnv *, jclass, jobject, jlong, jint, jobjectArray);

/*
 * Class:     com_sun_jna_Native
 * Method:    invokeLong
 * Signature: (Lcom/sun/jna/Function;JI[Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_jna_Native_invokeLong
  (JNIEnv *, jclass, jobject, jlong, jint, jobjectArray);

/*
 * Class:     com_sun_jna_Native
 * Method:    invokeVoid
 * Signature: (Lcom/sun/jna/Function;JI[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_invokeVoid
  (JNIEnv *, jclass, jobject, jlong, jint, jobjectArray);

/*
 * Class:     com_sun_jna_Native
 * Method:    invokeFloat
 * Signature: (Lcom/sun/jna/Function;JI[Ljava/lang/Object;)F
 */
JNIEXPORT jfloat JNICALL Java_com_sun_jna_Native_invokeFloat
  (JNIEnv *, jclass, jobject, jlong, jint, jobjectArray);

/*
 * Class:     com_sun_jna_Native
 * Method:    invokeDouble
 * Signature: (Lcom/sun/jna/Function;JI[Ljava/lang/Object;)D
 */
JNIEXPORT jdouble JNICALL Java_com_sun_jna_Native_invokeDouble
  (JNIEnv *, jclass, jobject, jlong, jint, jobjectArray);

/*
 * Class:     com_sun_jna_Native
 * Method:    invokePointer
 * Signature: (Lcom/sun/jna/Function;JI[Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_jna_Native_invokePointer
  (JNIEnv *, jclass, jobject, jlong, jint, jobjectArray);

/*
 * Class:     com_sun_jna_Native
 * Method:    invokeStructure
 * Signature: (Lcom/sun/jna/Function;JI[Ljava/lang/Object;JJ)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_invokeStructure
  (JNIEnv *, jclass, jobject, jlong, jint, jobjectArray, jlong, jlong);

/*
 * Class:     com_sun_jna_Native
 * Method:    invokeObject
 * Signature: (Lcom/sun/jna/Function;JI[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_sun_jna_Native_invokeObject
  (JNIEnv *, jclass, jobject, jlong, jint, jobjectArray);

/*
 * Class:     com_sun_jna_Native
 * Method:    open
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_jna_Native_open
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_sun_jna_Native
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sun_jna_Native
 * Method:    findSymbol
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_jna_Native_findSymbol
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_sun_jna_Native
 * Method:    indexOf
 * Signature: (Lcom/sun/jna/Pointer;JJB)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_jna_Native_indexOf
  (JNIEnv *, jclass, jobject, jlong, jlong, jbyte);

/*
 * Class:     com_sun_jna_Native
 * Method:    read
 * Signature: (Lcom/sun/jna/Pointer;JJ[BII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_read__Lcom_sun_jna_Pointer_2JJ_3BII
  (JNIEnv *, jclass, jobject, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_sun_jna_Native
 * Method:    read
 * Signature: (Lcom/sun/jna/Pointer;JJ[SII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_read__Lcom_sun_jna_Pointer_2JJ_3SII
  (JNIEnv *, jclass, jobject, jlong, jlong, jshortArray, jint, jint);

/*
 * Class:     com_sun_jna_Native
 * Method:    read
 * Signature: (Lcom/sun/jna/Pointer;JJ[CII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_read__Lcom_sun_jna_Pointer_2JJ_3CII
  (JNIEnv *, jclass, jobject, jlong, jlong, jcharArray, jint, jint);

/*
 * Class:     com_sun_jna_Native
 * Method:    read
 * Signature: (Lcom/sun/jna/Pointer;JJ[III)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_read__Lcom_sun_jna_Pointer_2JJ_3III
  (JNIEnv *, jclass, jobject, jlong, jlong, jintArray, jint, jint);

/*
 * Class:     com_sun_jna_Native
 * Method:    read
 * Signature: (Lcom/sun/jna/Pointer;JJ[JII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_read__Lcom_sun_jna_Pointer_2JJ_3JII
  (JNIEnv *, jclass, jobject, jlong, jlong, jlongArray, jint, jint);

/*
 * Class:     com_sun_jna_Native
 * Method:    read
 * Signature: (Lcom/sun/jna/Pointer;JJ[FII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_read__Lcom_sun_jna_Pointer_2JJ_3FII
  (JNIEnv *, jclass, jobject, jlong, jlong, jfloatArray, jint, jint);

/*
 * Class:     com_sun_jna_Native
 * Method:    read
 * Signature: (Lcom/sun/jna/Pointer;JJ[DII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_read__Lcom_sun_jna_Pointer_2JJ_3DII
  (JNIEnv *, jclass, jobject, jlong, jlong, jdoubleArray, jint, jint);

/*
 * Class:     com_sun_jna_Native
 * Method:    write
 * Signature: (Lcom/sun/jna/Pointer;JJ[BII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_write__Lcom_sun_jna_Pointer_2JJ_3BII
  (JNIEnv *, jclass, jobject, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_sun_jna_Native
 * Method:    write
 * Signature: (Lcom/sun/jna/Pointer;JJ[SII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_write__Lcom_sun_jna_Pointer_2JJ_3SII
  (JNIEnv *, jclass, jobject, jlong, jlong, jshortArray, jint, jint);

/*
 * Class:     com_sun_jna_Native
 * Method:    write
 * Signature: (Lcom/sun/jna/Pointer;JJ[CII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_write__Lcom_sun_jna_Pointer_2JJ_3CII
  (JNIEnv *, jclass, jobject, jlong, jlong, jcharArray, jint, jint);

/*
 * Class:     com_sun_jna_Native
 * Method:    write
 * Signature: (Lcom/sun/jna/Pointer;JJ[III)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_write__Lcom_sun_jna_Pointer_2JJ_3III
  (JNIEnv *, jclass, jobject, jlong, jlong, jintArray, jint, jint);

/*
 * Class:     com_sun_jna_Native
 * Method:    write
 * Signature: (Lcom/sun/jna/Pointer;JJ[JII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_write__Lcom_sun_jna_Pointer_2JJ_3JII
  (JNIEnv *, jclass, jobject, jlong, jlong, jlongArray, jint, jint);

/*
 * Class:     com_sun_jna_Native
 * Method:    write
 * Signature: (Lcom/sun/jna/Pointer;JJ[FII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_write__Lcom_sun_jna_Pointer_2JJ_3FII
  (JNIEnv *, jclass, jobject, jlong, jlong, jfloatArray, jint, jint);

/*
 * Class:     com_sun_jna_Native
 * Method:    write
 * Signature: (Lcom/sun/jna/Pointer;JJ[DII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_write__Lcom_sun_jna_Pointer_2JJ_3DII
  (JNIEnv *, jclass, jobject, jlong, jlong, jdoubleArray, jint, jint);

/*
 * Class:     com_sun_jna_Native
 * Method:    getByte
 * Signature: (Lcom/sun/jna/Pointer;JJ)B
 */
JNIEXPORT jbyte JNICALL Java_com_sun_jna_Native_getByte
  (JNIEnv *, jclass, jobject, jlong, jlong);

/*
 * Class:     com_sun_jna_Native
 * Method:    getChar
 * Signature: (Lcom/sun/jna/Pointer;JJ)C
 */
JNIEXPORT jchar JNICALL Java_com_sun_jna_Native_getChar
  (JNIEnv *, jclass, jobject, jlong, jlong);

/*
 * Class:     com_sun_jna_Native
 * Method:    getShort
 * Signature: (Lcom/sun/jna/Pointer;JJ)S
 */
JNIEXPORT jshort JNICALL Java_com_sun_jna_Native_getShort
  (JNIEnv *, jclass, jobject, jlong, jlong);

/*
 * Class:     com_sun_jna_Native
 * Method:    getInt
 * Signature: (Lcom/sun/jna/Pointer;JJ)I
 */
JNIEXPORT jint JNICALL Java_com_sun_jna_Native_getInt
  (JNIEnv *, jclass, jobject, jlong, jlong);

/*
 * Class:     com_sun_jna_Native
 * Method:    getLong
 * Signature: (Lcom/sun/jna/Pointer;JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_jna_Native_getLong
  (JNIEnv *, jclass, jobject, jlong, jlong);

/*
 * Class:     com_sun_jna_Native
 * Method:    getFloat
 * Signature: (Lcom/sun/jna/Pointer;JJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_sun_jna_Native_getFloat
  (JNIEnv *, jclass, jobject, jlong, jlong);

/*
 * Class:     com_sun_jna_Native
 * Method:    getDouble
 * Signature: (Lcom/sun/jna/Pointer;JJ)D
 */
JNIEXPORT jdouble JNICALL Java_com_sun_jna_Native_getDouble
  (JNIEnv *, jclass, jobject, jlong, jlong);

/*
 * Class:     com_sun_jna_Native
 * Method:    _getPointer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_jna_Native__1getPointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sun_jna_Native
 * Method:    getWideString
 * Signature: (Lcom/sun/jna/Pointer;JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sun_jna_Native_getWideString
  (JNIEnv *, jclass, jobject, jlong, jlong);

/*
 * Class:     com_sun_jna_Native
 * Method:    getStringBytes
 * Signature: (Lcom/sun/jna/Pointer;JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sun_jna_Native_getStringBytes
  (JNIEnv *, jclass, jobject, jlong, jlong);

/*
 * Class:     com_sun_jna_Native
 * Method:    setMemory
 * Signature: (Lcom/sun/jna/Pointer;JJJB)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_setMemory
  (JNIEnv *, jclass, jobject, jlong, jlong, jlong, jbyte);

/*
 * Class:     com_sun_jna_Native
 * Method:    setByte
 * Signature: (Lcom/sun/jna/Pointer;JJB)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_setByte
  (JNIEnv *, jclass, jobject, jlong, jlong, jbyte);

/*
 * Class:     com_sun_jna_Native
 * Method:    setShort
 * Signature: (Lcom/sun/jna/Pointer;JJS)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_setShort
  (JNIEnv *, jclass, jobject, jlong, jlong, jshort);

/*
 * Class:     com_sun_jna_Native
 * Method:    setChar
 * Signature: (Lcom/sun/jna/Pointer;JJC)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_setChar
  (JNIEnv *, jclass, jobject, jlong, jlong, jchar);

/*
 * Class:     com_sun_jna_Native
 * Method:    setInt
 * Signature: (Lcom/sun/jna/Pointer;JJI)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_setInt
  (JNIEnv *, jclass, jobject, jlong, jlong, jint);

/*
 * Class:     com_sun_jna_Native
 * Method:    setLong
 * Signature: (Lcom/sun/jna/Pointer;JJJ)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_setLong
  (JNIEnv *, jclass, jobject, jlong, jlong, jlong);

/*
 * Class:     com_sun_jna_Native
 * Method:    setFloat
 * Signature: (Lcom/sun/jna/Pointer;JJF)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_setFloat
  (JNIEnv *, jclass, jobject, jlong, jlong, jfloat);

/*
 * Class:     com_sun_jna_Native
 * Method:    setDouble
 * Signature: (Lcom/sun/jna/Pointer;JJD)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_setDouble
  (JNIEnv *, jclass, jobject, jlong, jlong, jdouble);

/*
 * Class:     com_sun_jna_Native
 * Method:    setPointer
 * Signature: (Lcom/sun/jna/Pointer;JJJ)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_setPointer
  (JNIEnv *, jclass, jobject, jlong, jlong, jlong);

/*
 * Class:     com_sun_jna_Native
 * Method:    setWideString
 * Signature: (Lcom/sun/jna/Pointer;JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_setWideString
  (JNIEnv *, jclass, jobject, jlong, jlong, jstring);

/*
 * Class:     com_sun_jna_Native
 * Method:    getDirectByteBuffer
 * Signature: (Lcom/sun/jna/Pointer;JJJ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_sun_jna_Native_getDirectByteBuffer
  (JNIEnv *, jclass, jobject, jlong, jlong, jlong);

/*
 * Class:     com_sun_jna_Native
 * Method:    malloc
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_jna_Native_malloc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sun_jna_Native
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sun_jna_Native
 * Method:    setDetachState
 * Signature: (ZJ)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Native_setDetachState
  (JNIEnv *, jclass, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
