/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_jna_Function */

#ifndef _Included_com_sun_jna_Function
#define _Included_com_sun_jna_Function
#ifdef __cplusplus
extern "C" {
#endif
#undef com_sun_jna_Function_MAX_NARGS
#define com_sun_jna_Function_MAX_NARGS 256L
#undef com_sun_jna_Function_C_CONVENTION
#define com_sun_jna_Function_C_CONVENTION 0L
#undef com_sun_jna_Function_ALT_CONVENTION
#define com_sun_jna_Function_ALT_CONVENTION 63L
#undef com_sun_jna_Function_MASK_CC
#define com_sun_jna_Function_MASK_CC 63L
#undef com_sun_jna_Function_THROW_LAST_ERROR
#define com_sun_jna_Function_THROW_LAST_ERROR 64L
#undef com_sun_jna_Function_USE_VARARGS
#define com_sun_jna_Function_USE_VARARGS 384L
#ifdef __cplusplus
}
#endif
#endif
